name: 'GT Editorial'
description: 'Common Editorial, CKE5, and image configurations'
type: 'Site'

recipes:
  - recipes/gt_mediaspace

install:
  - anchor_link
  - asset_injector

  - ckeditor5_paste_filter
  - ckeditor5_plugin_pack
  - ckeditor_responsive_table
  - ckeditor5_table_fix

  - diff
  - diff_plus

  - editor_advanced_link
  - editoria11y

  - linkchecker
  - linkit
  - linkpurpose
  - menu_link_attributes
  - node_revision_delete

  - quick_node_clone
  - scheduler
  - trash
  - url_embed
  - views_accordion

config:
  strict: false
  import:
    editoria11y: '*'
  actions:
    editoria11y.settings:
      simpleConfigUpdate:
        # Map tiles contain no alt text.
        # Skipping the map pane to limit reports
        # where the fix is outwith editors control.
        ignore_elements: '.leaflet-map-pane *'
