name: 'GT Editorial'
description: 'Common Editorial, CKE5, and image configurations'
type: 'Site'

recipes:
  - recipes/gt_mediaspace

install:
  - anchor_link

  - ckeditor5_paste_filter
  - ckeditor5_plugin_pack
  - ckeditor_responsive_table

  - diff
  - diff_plus

  - editor_advanced_link
  - editoria11y
  - linkchecker
  - linkit
  - linkpurpose

  - node_revision_delete
  - quick_node_clone
  - scheduler
  - trash
  - typography_filter
  - url_embed

  - oembed_lazyload
  - oembed_providers

  - blazy
  - crop
  - focal_point
  - imagemagick
  - svg_image

config:
  strict: false
  import:
    editoria11y: '*'
